############################
## CHANGE THESE
############################

baseURL: 'https://arodindev.github.io/'
title: 'arodindev blog'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'

